apps/events/urls.py
''' URLS for the events app. '''
from django.conf.urls import url, include
from rest_framework import routers
from .feeds import LatestEventsFeed, EventsICal

from . import views

app_name = 'events'

router = routers.DefaultRouter()
router.register(r'events', views.EventViewSet)

urlpatterns = [
    url(r'^$', views.EventList.as_view(), name='event-list'),
    url(r'detail/(?P<slug>[\w\-]+)/$', views.EventDetail.as_view(),
        name='event-detail'),
    url(r'add/$', views.EventCreate.as_view(), name='event-add'),
    url(r'delete/(?P<slug>[\w\-]+)/$', views.EventDelete.as_view(),
        name='event-delete'),

    url(r'location/(?P<slug>[\w\-]+)/$', views.LocationDetail.as_view(),
        name='location-detail'),
    url(r'location/list/', views.LocationList.as_view(), name='location-list'),

    url(r'feed/$', LatestEventsFeed()),
    url(r'ical/$', EventsICal()),
    #url(r'api/', include(router.urls))
]

navgames/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.sitemaps.views import sitemap
from django.views.static import serve

admin.autodiscover()

urlpatterns = [
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^select2/', include('django_select2.urls')),
]

urlpatterns += i18n_patterns(
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^liveresults/', include('liveresults.urls',
                                  namespace="liveresults")),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^', include('cms.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = [
        url(r'^media/(?P<path>.*)$', serve,  # NOQA
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ] + staticfiles_urlpatterns() + urlpatterns  # NOQA

apps/events/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.utils import timezone
from cms.models import CMSPlugin
from cms.models.fields import PlaceholderField

# TODO: flesh out. Street address and/or coordinates?
class Location(models.Model):
    ''' A location for an event.'''
    name = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    maplink = models.URLField(blank=True)
    description = models.TextField(blank=True)
    map_placeholder = PlaceholderField('map')
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Location, self).save(*args, **kwargs)

    def __str__(self):
        return self.name + ', ' + self.city


# TODO: active? Date range? more info?
class Series(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name_plural = 'Series'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Series, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class PastEvents(models.Manager):
    def get_queryset(self):
        return super(PastEvents, self).get_queryset() \
                .filter(start_date__lte=timezone.now())


class FutureEvents(models.Manager):
    def get_queryset(self):
        return super(FutureEvents, self).get_queryset() \
                .filter(start_date__gte=timezone.now())


class Event(models.Model):
    ''' Event information, including times and description.'''
    name = models.CharField(max_length=100, blank=True)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField(null=True, blank=True)
    location = models.ForeignKey(Location)
    description = models.TextField()
    uses_epunch = models.BooleanField()
    series = models.ForeignKey(Series, null=True, blank=True)
    public = models.BooleanField()
    slug = models.SlugField(unique=True, blank=True)
    image = models.ImageField(upload_to='event_images', null=True, blank=True)
    customURL = models.URLField(null=True, blank=True)

    objects = models.Manager()
    past_events = PastEvents()
    future_events = FutureEvents()

    @property
    def future(self):
        now = timezone.now()
        return self.start_date > now

    @property
    def past(self):
        now = timezone.now()
        return self.start_date < now

    def save(self, *args, **kwargs):
        if not self.slug:
            if not self.name:
                slugname = self.location.name + \
                           ' ' + self.start_date.strftime("%Y-%m-%d")
                self.slug = slugify(slugname)
            else:
                slugname = self.name + ' ' + \
                           self.start_date.strftime("%Y-%m-%d")
                self.slug = slugify(slugname)
        super(Event, self).save(*args, **kwargs)

    def __str__(self):
        if not self.name:
            descrip = self.location.name + ' (' + str(self.start_date) + ')'
        else:
            descrip = self.name + ', ' + ' (' + str(self.start_date) + ')'
        return descrip


class Club(models.Model):
    name = models.CharField(max_length=100, unique=True)
    short_name = models.CharField(max_length=10, unique=True)

    SCHOOL = 'S'
    CLUB = 'C'
    KIND_CHOICES = (
        (SCHOOL, 'School'),
        (CLUB, 'Club'),
    )
    kind = models.CharField(
        max_length=1,
        choices=KIND_CHOICES,
        default=SCHOOL)

    def __str__(self):
        return self.name


class Course(models.Model):
    event = models.ForeignKey(Event)
    name = models.CharField(max_length=20, null=True, blank=True)
    short_name = models.CharField(max_length=10)
    length = models.FloatField(null=True, blank=True)

    TIME = 'T'
    SCORE = 'S'
    BOTH = 'B'
    KIND_CHOICES = (
        (TIME, 'Time'),
        (SCORE, 'Score'),
        (BOTH, 'Both'),
    )
    kind = models.CharField(
        max_length=1,
        choices=KIND_CHOICES,
        default=TIME)

    def __str__(self):
        return '{}: {}'.format(self.event, self.name)


class Result(models.Model):
    '''Single result, with time represented AP-style (hhmmss).'''
    place = models.IntegerField(null=True, blank=True)
    course = models.ForeignKey(Course, null=True, blank=True)
    team_name = models.CharField(max_length=100)
    club = models.ForeignKey(Club, null=True, blank=True)
    points = models.IntegerField(null=True, blank=True)
    time = models.CharField(max_length=6, null=True, blank=True)
    time_seconds = models.IntegerField(null=True, blank=True)

    OK = 'OK'
    DNF = 'DNF'
    DNS = 'DNS'
    MSP = 'MSP'
    STATUS_CHOICES = (
        (OK, 'OK'),
        (DNF, 'DNF'),
        (DNS, 'DNS'),
        (MSP, 'MSP'),
    )
    status = models.CharField(
        max_length=5,
        choices=STATUS_CHOICES,
        default=OK)

    def get_time(self):
        '''Returns the elapsed time as formatted string.'''
        if len(self.time) % 2:
            time = '0' + self.time
            odd = True
        else:
            time = self.time
            odd = False

        time = ':'.join(time[i:i+2] for i in range(0, len(time), 2))
        if odd:
            time = time[1:]
        return time

    #def save(self):
        #''' Convert time (AP-style) to seconds for time_seconds.'''
    #    pass


class EventPluginModel(CMSPlugin):
    event = models.ForeignKey(Event)

    def __str__(self):
        return self.event.name


class EventListPluginModel(CMSPlugin):
    num_events = models.IntegerField(default=5)
    only_public = models.BooleanField(default=True)
    past_events = models.BooleanField(default=False)
    future_events = models.BooleanField(default=True)
    series = models.ForeignKey(Series, null=True, blank=True)

    def __str__(self):
        if self.past_events:
            descrip = 'Last '
        else:
            descrip = 'Next '
        if self.only_public:
            descrip += ' public '
        return descrip + str(self.num_events) + ' events.'


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    club = models.ForeignKey(Club, null=True, blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

apps/events/forms.py
from django.forms import ModelForm
from django.core.urlresolvers import reverse
from django.core.auth.models import User
from django import forms
from .models import Event, Location, Series, UserProfile


class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = ['name', 'start_date', 'end_date',
                  'location', 'description', 'series']

    def get_absolute_url(self):
        return reverse('detail', kwargs={'slug': self.slug})


class UserForm(ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ('club', 'school')

apps/events/views.py
from itertools import chain
from operator import attrgetter

from django.utils.translation import ugettext_lazy as _
from django.views import generic
from django.core.urlresolvers import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from cms.utils.urlutils import admin_reverse
from rest_framework import viewsets, permissions

from .models import Event, Location
from .serializers import EventSerializer


class LocationList(generic.ListView):
    template_name = 'events/location_list.html'
    context_object_name = 'location_list'

    def get_queryset(self):
        return Location.objects.all()


class LocationDetail(generic.DetailView):
    model = Location
    fields = ['name', 'city', 'description']


class EventList(generic.ListView):
    template_name = 'events/event_list.html'
    context_object_name = 'event_list'

    def get_queryset(self):
        ''' Return all upcoming events '''
        future_events = Event.future_events.all().order_by('start_date')
        if len(future_events) < 5:
            past_events = Event.past_events.all().order_by('-start_date')[:4]
            events = sorted(
                chain(future_events, past_events),
                key=attrgetter('start_date'))
        else:
            events = future_events
        return events


class EventCreate(CreateView):
    model = Event
    fields = ['name', 'start_date', 'end_date',
              'location', 'description', 'series', 'uses_epunch']
    success_url = reverse_lazy('index')


class EventUpdate(UpdateView):
    model = Event
    fields = ['name', 'start_date', 'end_date',
              'location', 'description', 'series']


class EventDelete(DeleteView):
    model = Event
    success_url = reverse_lazy('index')


class EventDetail(generic.DetailView):
    model = Event
    template_name = 'events/detail.html'
    pk_url_kwarg = True

    def get_object(self):
        object = super(EventDetail, self).get_object()

        # Add an edit item to the CMS toolbar for this event
        menu = self.request.toolbar.get_or_create_menu('events-app', _('Events'))
        menu.add_sideframe_item(
            name=_('Edit this event'),
            url=admin_reverse('events_event_change', args=[object.pk]))

        return object

    # def get_queryset(self):
    #     self.event = get_object_or_404(Event, slug=self.kwargs['slug'])
    #     return self.event


class EventViewSet(viewsets.ModelViewSet):
    queryset = Event.future_events.all().order_by('start_date')
    serializer_class = EventSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

navgames/templates/events/detail.html
{% extends 'base.html' %}
{% load cms_tags staticfiles thumbnail %}

{% block title %}{% endblock %}

{% block content %}
<div class="container">

    <div class="row">
        <div class="col-sm-12">
            <h1>{{ event.name }}</h1>
        </div>
        
        <div class="col-sm-9">
            <h4>{{ event.location }} - {{ event.start_date|date:"D d M, Y" }}</h4>
            <hr>

            {% if event.public %}
                <div class="alert alert-info" role="alert">
                    <strong>All welcome!</strong> This event is open to the public!
                </div>
            {% endif %}
            
            <img src="{% thumbnail event.image 600x300 crop subject_location=event.image.subject_location %}" 
                 alt="{{ event.image.alt }}"> 
            
            <p>Start: {{ event.start_date|date:"g:iA" }}</p>
            {% render_model event "description" %}

            {% if event.uses_epunch %}
                <div><br /><p><strong>This event uses e-punch</strong></p></div>
            {% endif %}

            <h2>Location</h2>
            <div class="row">
                <div class="col-sm-6">
                    {% render_model event.location "description" %}
                </div>
                <div class="col-sm-6">
                    {% render_placeholder event.location.map_placeholder %}
                </div>
            </div>

            <!-- results -->            
            <h2>Results</h2>
            <div clas="row">            
                {% if event.future %}
                    You'll be able to view results here after the event.
                {% else %}
                    {% for course in event.course_set.all %}
                        <h3>{{ course.name }}</h3>
                        <table class="table table-responsive table-striped">
                            <thead>
                                <th>Place</th>
                                <th>Name</th>
                                <th>Club</th>
                                <th>Points</th>
                                <th>Time</th>
                            </thead>
                            {% for result in course.result_set.all %}
                                <tr><td>{{ result.place }}</td>
                                    <td>{{ result.team_name }}</td>
                                    <td>{% if result.club %} {{ result.club }}{% endif %}</td>
                                    <td>{% if result.points %} {{ result.points }}{% endif %}</td>
                                    <td>{% if result.time %} {{ result.get_time }}{% endif %}</td>
                                </tr>
                            {% endfor %}
                        </table>
                    {% endfor %}
                {% endif %}
            </div>
        </div>


        <!-- sidebar -->
        <div class="col-sm-3 hidden-xs">
            <div class="well">
                <div class="info-box-item">
                    <img class="center-block img-responsive" src="{{ STATIC_URL }}/icons/question.png">
                    <a href="{% page_url 'newcomers' %}"><h3 class="text-center">How it works</h3></a>
                    <p class="text-center">What to expect at an event</p>
                </div>

                <div class="info-box-item">                
                    <img class="center-block img-responsive" src="{{ STATIC_URL }}/images/legend-text.png">
                    <a href="{{ STATIC_URL }}/images/orienteering-map-legend.jpg" class="text-center"><h3>Map legend</h3></a>
                    <p class="text-center">Orienteering maps use special symbols to depict forest, fields, trails, boulders, and building.</p>
                </div>

                <div class="info-box-item">                
                    <img class="center-block img-responsive" src="{{ STATIC_URL }}/images/e-punch.png">
                    <a href="{% page_url 'newcomers' %}" class="text-center"><h3>E-punch</h3></a>
                    <p class="text-center">Each participant uses an electronic finger stick to keep track of the checkpoints they've punched and their time on the course.</p>
                </div>

            </div>
        </div>
        <!-- end sidebar -->

    </div>

    <div class="row">
    </div>
{% endblock content %}